channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.7
  - doc8
  - flake8
  - jmespath
  - jsonschema
  - sphinx
  - sphinx_rtd_theme
  - pytest
  - pytest-cov
  - python-build
  - python-dateutil
  - pyyaml
