channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.7
  - doc8
  - flake8
  - jmespath
  - jsonschema
  - sphinx<8
  - sphinx_rtd_theme<3
  - pytest
  - pytest-cov
  - python-build
  - python-dateutil
  - ruamel.yaml
