name: Python application

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install flake8 pytest pytest-cov
          python3 -m pip install -r ./requirements.txt
      - name: Install package
        run: |
          python3 -m pip install .
      - name: Lint with flake8
        run: |
          flake8 . --show-source --statistics
      - name: Test with pytest
        run: |
          pytest --cov
